const jobData = [
    { title: "Job 1", company: "Company 1" },
    { title: "Job 2", company: "Company 2" },
    { title: "Job 3", company: "Company 3" },
    { title: "Job 4", company: "Company 4" },
    { title: "Job 5", company: "Company 5" },
    { title: "Job 6", company: "Company 6" },
    { title: "Job 7", company: "Company 7" },
    { title: "Job 8", company: "Company 8" },
    { title: "Job 9", company: "Company 9" },
    { title: "Job 10", company: "Company 10" },
    { title: "Job 11", company: "Company 11" },
    { title: "Job 12", company: "Company 12" },
    { title: "Job 13", company: "Company 13" },
    { title: "Job 14", company: "Company 14" },
    { title: "Job 15", company: "Company 15" },
    { title: "Job 16", company: "Company 16" },
    { title: "Job 17", company: "Company 17" },
    { title: "Job 18", company: "Company 18" },
    { title: "Job 19", company: "Company 19" },
    { title: "Job 20", company: "Company 20" },
    { title: "Job 21", company: "Company 21" },
    { title: "Job 22", company: "Company 22" },
    { title: "Job 23", company: "Company 23" },
    { title: "Job 24", company: "Company 24" },
    { title: "Job 25", company: "Company 25" },
    { title: "Job 26", company: "Company 26" },
    { title: "Job 27", company: "Company 27" },
    { title: "Job 28", company: "Company 28" },
    { title: "Job 29", company: "Company 29" },
    { title: "Job 30", company: "Company 30" },
  ];

export default jobData